### ISSUE TITLE
Support YAML front matter?

### ISSUE THREAD

**Issue by nick-thompson** [jgallen23/markx#4]
Hey dude! Thanks for this awesome project!

Do you think it'd be possible to support YAML front matter on markdown pages?
https://github.com/mojombo/jekyll/wiki/YAML-Front-Matter

It feels kind of unnecessary to have to write an additional file to specify data.

On a similar note, it might be cool to pass in default information about the file to the template. Like reading the file name and the last modified time with fs.stat, and passing those into the template renderer. That way, you wouldn't necessarily have to provide additional data to specify basic properties.

Just throwing my thoughts out, what do you think?

**Comment by jgallen23** [comment]
Great idea.  I don't have time right now though. Pull requests welcome :)

**Comment by nick-thompson** [comment]
Opened a pull request to address this issue:
cc #5 

(Accidentally closed this issue a second ago referencing the wrong issue number. My bad :P )
